### PR TITLE
Clang.jl generated bindings and internal refactor

### PR DESCRIPTION
**Pull request by metab0t**
A first step of https://github.com/JuliaDatabases/SQLite.jl/pull/295

1. Use Clang.jl to generate C bindings automatically
2. Use WeakKeyDict to record prepared statements of a DB
3. Upgrade Julia version requirement to 1.6

All tests pass locally.

### CODE REVIEW

**Comment by metab0t** [comment]
@quinnj
JuliaFormatter.jl causes extra diff but the `runtests.jl` is almost unaffected except for removal of `SQLite.isready(::Stmt)`.
So maybe we can merge it as long as CI is green?

**Comment by metab0t** [comment]
The formatter causes a lot of noisy diffs, I can open another PR to format existing code as Step 0 then merge this PR if we agree on the formatter style configuration.

**Comment by metab0t** [comment]
@quinnj 
Now https://github.com/JuliaDatabases/SQLite.jl/pull/297 has merged. The diff is nicer to review except for 3k+ lines added by automatically generated C API bindings 😂

**Review by quinnj — APPROVED** [review]
This is great; thanks @metab0t!

**Pull request merged**
