### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by kescobo**
As promised on discourse - I've added `SQLite.esc_id()` to the docs output. 

Also, I fixed the signature for the doc string (`String` -> `AbstractString`), and fixed some minor formatting stuff.

### CODE REVIEW

**Comment by quinnj** [comment]
Thanks! I'm not sure I understand why other files got changed here other than the `esc_id` doc?

**Comment by kescobo** [comment]
Hmm - nothing in `docs/build` should be committed - it looks like you've commited to it in the past, and I did a `git commit -a` at one point. I've removed `docs/build` and added it to `.gitignore`. 

`src/SQLite.jl` is changed just to make the docstring for `esc_id` match the actual function signature (docstring said `String`, but the methods are defined for `AbstractString`).

**Comment by kescobo** [comment]
@quinnj I've noticed a couple of other places the docstring doesn't match the function signature (eg [here](https://github.com/JuliaDatabases/SQLite.jl/blob/master/src/SQLite.jl#L350-L355) and [here](https://github.com/JuliaDatabases/SQLite.jl/blob/master/src/SQLite.jl#L365-L369)), and some things I think could be a bit clearer. Would you prefer separate PRs, or should I add them here?

Otherwise, is there anything else you'd like me to address here?

**Comment by quinnj** [comment]
@kescobo, I'd definitely appreciate the cleanups here! In fact, cleaning up the docs for this package has been on my TODO list for a while now.....anything you're willing to contribute would be happily accepted! Thanks!

**Comment by kescobo** [comment]
Ok, you got it! Are you also ok with changing the current copied docs to more auto-docs?

**Comment by quinnj** [comment]
Yes, definitely. Go to town. I've recently been trying to figure out the latest Documenter best practices, so if you already know and can update here, that'd be great.

**Comment by kescobo** [comment]
Still work in progress - latest commits moves a lot of the docs in `docs/src/index.md` into docstrings inside the source code and using `@docs` block. Also:

- I added `@refs` to link between a bunch of the stuff
- I added [semantic line breaks](https://sembr.org/) to a lot of the markdown

Outstanding issues:

1. I'm not sure how to deal with the types (like `SQLite.Query`) that have inner constructors - I haven't figured out how to deal with those to have separate docs for the type and for the constructor
2. I think it would be worth splitting the pages up just a little so that it's not one long page. The cross-references help a bit, but it could be cleaner
3. For the examples that are included, it would be nice to have them evaluated by documenter and create doctests. This might be a separate PR though.

**Comment by quinnj** [comment]
Thanks so much @kescobo; I really appreciate your help w/ the docs here. For 1. I'd say don't worry about the inner constructor; I have the docs later on one of the outer constructors. For 2. I agree, but we can do this later. Also 3. can be done later.

I'm inclined to merge now and we can clean up more later. Sound good?

**Comment by kescobo** [comment]
My pleasure! Glad to help. I'm ok if you want to merge this now, and do the other things as separate PRs.

**Comment by quinnj** [comment]
Thanks! I've got some big changes coming down the pipeline w/ a few new database interface packages, so I want to get another release out before doing a 1.0 w/ those bigger changes.

**Pull request merged**
