### PR TITLE
Fixing typestability issues atleast with commonly used types

### PR DESCRIPTION
**Pull request by yellowflash**
`getvalue` in it's current form seem super slow. This somehow improved the performance (atleast in my usecase) by upto 2x. 

I am a noob julia programmer, I am not sure how those dynamic fields are implemented with Tables.jl. Somehow if I access it via `Tables.getcolumn` versus `row.field` there is a 6-8x performance gain.

### CODE REVIEW

**Comment by quinnj** [comment]
Hmmm, because we have
```julia
function getvalue(q::Query, col::Int, rownumber::Int, ::Type{T}) where {T}
```
it should effectively be compiling a new method for every different value of `T` that is passed, so I don't think this PR should be changing anything materially.

Can you share some code snippets where you're seeing the performance problems? I'm happy to take a look. It's been a while since we've tightened the screws on performance in this package.

**Comment by yellowflash** [comment]
Oh pardon me, 

```
TT = juliatype(t) # native SQLite Int, Float, and Text types
return sqlitevalue(ifelse(TT === Any && !isbitstype(T), T, TT), handle, col)
```

would have to compiled to a dynamic dispatch right? Since the type is not known at compile time.

**Comment by yellowflash** [comment]
@quinnj Sorry for the mention. But did I answer your question? Is this still a concern?

**Comment by quinnj** [comment]
@yellowflash, thanks for the ping! And sorry for the slow response! So I have an idea of an alternative way to get the same results here; would you mind reviewing https://github.com/JuliaDatabases/SQLite.jl/pull/304 and maybe run your performance test and see how it fares? Basically you can pass `strict=true` and it should result in a more type-stable way to fetch results.

**Comment by yellowflash** [comment]
@quinnj Thank you, that MR seem like a much nicer fix for the type stability problem that what I did I think. I will try to test that out over the weekend, let's close this PR.

**Pull request closed without merging**
