### PR TITLE
fix string outputs from UDF

### PR DESCRIPTION
**Pull request by aplavin**
Not sure why "+1" was there, but it lead to an extra nul byte at the end.

### CODE REVIEW

**Comment by ImreSamu** [comment]
Maybe related issue:  https://github.com/JuliaDatabases/SQLite.jl/issues/147 ?

**Comment by aplavin** [comment]
Yes, I believe that issue is exactly what I fix here. The `+1` lead to trailing `00` as seen in your hex outputs.

**Review by quinnj — APPROVED** [review]
Thanks for the fix! Looks like the same `only` issue as the other PR.

**Comment by quinnj** [comment]
Ah shoot, looks like `only` wasn't introduced until Julia 1.4, so we still have the error.

**Pull request merged**
