### PR TITLE
update to new SQLiteBuilder build

### PR DESCRIPTION
**Pull request by visr**
This updates the SQLite version from 3.24 to 3.28 ([changes](https://www.sqlite.org/draft/changes.html))

Ref https://github.com/JuliaDatabases/SQLiteBuilder/pull/1

### CODE REVIEW

**Comment by quinnj** [comment]
@visr , sorry for the delay here; what's the status?

**Comment by visr** [comment]
This is good to go. After rebasing the tests pass, so those were fixed elsewhere.

**Comment by visr** [comment]
bump

**Comment by quinnj** [comment]
Great; thanks for the reminder! Sorry to be so slow in merging this.

**Pull request merged**
