### PR TITLE
Add Refs to bound values to avoid premature garbage collection (#180)

### LINKED ISSUE #180: bound values may get garbage collected while iterating query results
When binding parameters, SQLite.jl does not hold any reference to the bound values, but passes pointers to them to the C library. If the last Julia reference to a bound value is lost before/while iterating the query, the bound value will get garbage collected.

This leads to strange effects (missing results, results that don't match the query criteria, maybe segfaults) because the C library has a pointer to invalid data.

Side note: This also happens if the bytes of a bound value are changed, but that's somewhat reasonable.

Example code with enforced garbage collection to make it reproducible:

```julia
using SQLite

param = "Hello!"
query = SQLite.Query(SQLite.DB(), "SELECT ?1 UNION ALL SELECT ?1", values = [param])
param = "x"
for row in query
    println(row[1])
    GC.gc()
end
```

Expected output:
```
Hello!
Hello!
```

Actual output:
```
Hello!
<gibberish or nothing at all>
```

### PR DESCRIPTION
**Pull request by chschu**
This PR fixes #180 by keeping a reference to all currently bound parameter values in the `Stmt`.

Also, it fixes an issue with BLOB deserialization on Julia 1.2 which made the tests fail.

### CODE REVIEW

**Comment by quinnj** [comment]
@chschu, thanks for this PR; did you get a chance to look at the windows failures? Looks like the 32-bit builds both fail on something.

**Comment by chschu** [comment]
@quinnj I did take a look, but I don't have a clue why (only) the 32-bit build fail. It can probably be fixed by not using `.==` and comparing element-wise inside the brackets. This seems to work in other places.

I can try to fix it here in the next few days. Independently, I'll try to reproduce the problem on a 32-bit VM. Might be an issue with 32-bit builds of Julia.

**Comment by chschu** [comment]
Might have something to do with the issue: The log output on AppVeyor says it fails on the expression `all([i for i = r[1]] .== rng)` in runtests.jl:83, but that line reads `@test all([i for i in r[1]] .== rng)`.

**Comment by chschu** [comment]
Okay, so collecting the `StepRange{Date,Day}` range into an `Array{Date,1}` before performing the broadcast comparison seems to fix the problem with x86 builds.

**Comment by chschu** [comment]
The locking issue that occurs now seems to be caused by the `"pragma table_info($nm)"` in one of the `load!` methods. If the table exists (as it does at `runtests.jl:71`), the `Stmt` seems to lock the table until it is finalized/closed (e.g. by the garbage collector), which makes the call to `drop!` at `runtests.jl:76` fail sometimes.

I was able to reproduce that by putting a loop around all of the tests, which usually failed during the 2nd iteration.

The locking issue could be avoided by explicitly closing the `Stmt` after it has been executed. This could be done by using `execute!(::DB, ::AbstractString)` and immediately finalizing/closing the `Stmt` there.

**Comment by quinnj** [comment]
Thanks @chschu for all your work on this and fighting through the non-related test issues!

**Pull request merged**
