### PR TITLE
Retry macro for handling locked databases

### PR DESCRIPTION
**Pull request by squaregoldfish**
This is the first attempt at a retry macro, which appears to work in initial testing. There are several things I need to work out though, some of which need answers from the package authors:

* Where should the macro go in the source code? I was tempted to put it in `consts.jl` with the other macros, but they all seem to be internal only.
* I'm not very happy with the `database is locked` error detection. It works, but relies on parsing the error message. I see there's an `SQLITE_LOCKED` constant defined, but it doesn't appear to be used anywhere. Can we do anything with that?
* I haven't written any tests yet. I need to look into ways to explicitly lock the database to reliably trigger the macro's functionality.
* The macro sleeps for 0.001s before retrying. It should wait a random amount of milliseconds.
* The timeout should be customisable. Is one second too short for a default?
* I'm inclined to rename the macro to `lockretry` so it's a bit more obvious what it's retrying.

### CODE REVIEW

**Comment by squaregoldfish** [comment]
**Update 2019-03-31**

* Renamed macro to `lockretry`
* The sleep between retries is a random period between 0 and 1 seconds (should this have a smaller maximum?)
* The timeout is customisable

I think I need feedback at this point on the questions above.

**Comment by quinnj** [comment]
Sorry for the slow response here.

* You can just put the macro in the top level `SQLite.jl` file for now, at the very bottom
* As opposed to looking at the error message string, you could enhance `SQLiteException` to include an error code integer field and call [`sqlite3_errcode`](https://sqlite.org/c3ref/errcode.html) on the db.handle to get it in our definition of `sqliteerror`. You could then be more precise by finding the right [return/error code](https://sqlite.org/rescode.html) that correctly shows the database is locked
* I agree the retry delay should be configurable, as well as the number of retries. You could look at some of the code [here](https://github.com/JuliaWeb/Retry.jl) for inspiration (definitely doesn't need to be super complicated)
* I'm fine w/ `retry` or `lockretry`, both sound good to me

**Comment by squaregoldfish** [comment]
I'm satisfied that this works now - just looking into writing some tests.

A note on `NON_SQLITE_ERROR`:
I wanted to use the constant in the `SQLiteException` definition, but I can't include `consts.jl` before this be cause it depends on `SQLiteException` already having been declared. So I've used the raw value in the exception definition, but people can use the constant when they write code.

**Comment by squaregoldfish** [comment]
The busy_timeout option (#218) seems to be the preferred solution here. I'll close this.

**Pull request closed without merging**
